
#GROUP MEMBERS
#ALBIN THOMAS ,07
#ALEX P.L ,09
#ALEN K VARGHESE ,08
#BOBBY JOSEPH MATHEWS ,21

# Project: Optimal Career Prediction System

# ANALYSIS OF DIFFERENT SUPERVISED MACHINE LEARNING  ALGORITHMS



# SCIENCE DATASET: 4.5 LAKH



In [27]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import time

#DISPLAY TOP 5 ROWS
data = pd.read_csv("C:\\machine\\science-dataset.csv")
data.head(10)

IQ   PHYSICS  CHEMISTRY     MATHS   BIOLOGY  COMPUTER  LANGUAGE  \
0 -1.008651 -0.646053   1.483130 -0.491651 -0.420337  0.029624 -0.099065   
1 -0.516545  3.135103  -1.042419 -1.371282  0.088652 -0.926914  1.186076   
2  1.330520 -0.449276  -0.746021 -0.224562 -0.511844 -0.068503 -0.488076   
3 -1.443553 -0.209296   0.475726 -0.255531  1.069152  0.152201 -1.291762   
4  0.893850  0.374306   0.951791 -0.698985 -0.415257 -1.542616 -0.750294   
5 -2.798029 -0.337010   1.689635  1.549443 -1.097144  0.743820  1.420239   
6  1.689498  1.414032  -0.689225 -0.377121 -0.014630  1.350241 -0.935422   
7 -1.772473  0.228136  -0.161365  0.003763 -0.084336  0.061549 -0.512891   
8 -1.087134  0.165049   1.351920  0.126517  0.284113  0.917127 -1.589489   
9  1.577735  1.214914   0.540939 -0.703580  0.295974  1.035918 -1.112798   

   OPENNESS  CONSCIENTIOUSNESS  EXTRAVERSION  ...  SATISFACTION  \
0  1.703846          -1.874724     -0.747657  ...      0.223245   
1 -0.148570           1.267581     -0.104341  ...     -0.733354   
2 -0.456048          -0.329565      0.672229  ...      0.746915   
3 -0.817565          -0.159006     -1.424354  ...     -0.311611   
4  1.453135          -1.727244      0.728515  ...     -1.227262   
5  0.179937          -0.467669      0.201903  ...     -0.142162   
6 -1.031317           0.531610     -1.258476  ...     -0.110366   
7 -0.611300          -1.361522     -0.400869  ...     -1.114975   
8  0.568392           0.772986      1.848414  ...      0.950024   
9  1.109826           1.646882      0.705301  ...      0.699247   

   SOCIO-ECONOMIC-FACTORS   M-SCORE  TEAM-WORK  COMPETIVE-EXAM-WINNER  \
0               -2.721022  1.265528   0.119911               0.566785   
1               -0.983299 -0.672728  -0.564505              -0.895462   
2               -1.010269  0.278442   0.257752              -0.151023   
3               -0.454171 -0.084505  -0.025262              -1.126085   
4                0.940326 -0.991811   1.142285               0.247072   
5                0.456954 -0.695542   0.326168              -1.191192   
6                0.173484 -0.180160   0.114790               0.944251   
7                1.174844  1.744942   1.237503               0.699977   
8                0.084734 -0.423183  -0.384590              -0.074684   
9                1.113481 -1.030284  -0.984026              -0.914930   

   LEADERSHIP-SKILL  WORK-LIFE-BALANCE  CERTIFICATIONS  \
0         -1.951926           1.116503       -1.483536   
1         -0.296227           0.455496       -1.440636   
2          0.304002          -0.218066        1.044610   
3         -0.708699          -1.100454        0.500687   
4          0.467854          -0.131504       -0.165085   
5         -0.989191           0.143072        1.060792   
6         -0.250260          -0.395578       -1.557932   
7          1.508119           0.644319       -1.448363   
8          0.696934           0.133869        0.728442   
9          1.690874          -1.765382       -1.050837   

   SELF-LEARNING-CAPABILITY  CAREER  
0                  0.617054       1  
1                 -0.353796       0  
2                  1.421632       2  
3                 -0.726287       1  
4                 -1.098174       2  
5                  0.965897       2  
6                 -1.943085       0  
7                 -1.502030       0  
8                 -0.155451       1  
9                 -0.431092       1  

[10 rows x 23 columns]

In [28]:
X=data.drop(['CAREER'], axis = 1).values
#data.drop(['name'])
from sklearn import preprocessing 
Standardisation = preprocessing.StandardScaler() 
AFTER_SCALE= Standardisation.fit_transform(X) 
X=AFTER_SCALE
print(X)
y = data['CAREER']
print(X.shape)
print(y.shape)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=0)




[[-1.01022323e+00 -6.45237302e-01  1.11300196e+00 ...  1.11706852e+00
  -1.48495673e+00  6.17447285e-01]
 [-5.17847197e-01  3.13543283e+00 -7.81765445e-01 ...  4.55098220e-01
  -1.44202551e+00 -3.53916847e-01]
 [ 1.33023274e+00 -4.48486098e-01 -5.59395959e-01 ... -2.19445277e-01
   1.04505909e+00  1.42245191e+00]
 ...
 [ 2.99809168e-02  1.63595665e-01  6.00358124e-01 ...  6.96918721e-01
  -1.15012005e+00  5.91665972e-01]
 [ 8.01600072e-02  4.00059078e-01  1.33510530e+00 ... -6.37413053e-01
   1.97773150e-03  5.83187598e-01]
 [-1.76164381e+00  7.60466658e-02 -2.21542851e-01 ... -1.21197124e+00
  -1.27333845e+00 -2.70203358e-01]]
(450000, 22)
(450000,)


In [23]:
#NAIVE  BAYES
import time
start=time.time()
import sklearn.metrics as metrics
from sklearn.naive_bayes import GaussianNB
naive=GaussianNB()
naive.fit(X_train,y_train)
y_pred = naive.predict(X_test)
print("'NAIVE-BAYES-ACCURACY => "+str(metrics.accuracy_score(y_test, y_pred)*100)+str(" %"))
end=time.time()
print("Time=",end-start)

#CLASSIFICATION REPORT
from sklearn.metrics import classification_report,confusion_matrix
#CONFUSION MATRIX
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))



'NAIVE-BAYES-ACCURACY => 86.3725 %
Time= 0.1529829502105713
[[11226   427  1645]
 [   93 13000   345]
 [ 2320   621 10323]]


              precision    recall  f1-score   support

           0       0.82      0.84      0.83     13298
           1       0.93      0.97      0.95     13438
           2       0.84      0.78      0.81     13264

    accuracy                           0.86     40000
   macro avg       0.86      0.86      0.86     40000
weighted avg       0.86      0.86      0.86     40000



In [18]:
#logistic regression
import time
start=time.time()
from sklearn import linear_model
log=linear_model.LogisticRegression()


log.fit(X_train,y_train)
y_pred=(log.predict(X_test))
print("LOGISTIC-REGRESSION-ACCURACY => "+str(metrics.accuracy_score(y_test, y_pred)*100)+str(" %"))
end=time.time()
print("time=",end-start)
#CLASSIFICATION REPORT
from sklearn.metrics import classification_report,confusion_matrix
#CONFUSION MATRIX
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

LOGISTIC-REGRESSION-ACCURACY => 84.75222222222222 %
time= 4.109047889709473
[[24605  2468  3058]
 [ 2746 25677  1508]
 [  954  2989 25995]]


              precision    recall  f1-score   support

           0       0.87      0.82      0.84     30131
           1       0.82      0.86      0.84     29931
           2       0.85      0.87      0.86     29938

    accuracy                           0.85     90000
   macro avg       0.85      0.85      0.85     90000
weighted avg       0.85      0.85      0.85     90000



In [16]:
#two hidden layers

import time
start=time.time()

from sklearn.neural_network import MLPClassifier
mlp= MLPClassifier(hidden_layer_sizes=(8,8), activation='relu', solver='adam',max_iter=200)
mlp.fit(X_train,y_train)
y_pred=(mlp.predict(X_test))
print("MLP-ACCURACY => "+str(metrics.accuracy_score(y_test, y_pred)*100)+str(" %"))
end=time.time()
print("time="+str(end-start))

#CLASSIFICATION REPORT
from sklearn.metrics import classification_report,confusion_matrix
#CONFUSION MATRIX
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

MLP-ACCURACY => 92.19888888888889 %
time=336.13990092277527
[[27214   919  1998]
 [  835 27624  1472]
 [  685  1112 28141]]


              precision    recall  f1-score   support

           0       0.95      0.90      0.92     30131
           1       0.93      0.92      0.93     29931
           2       0.89      0.94      0.91     29938

    accuracy                           0.92     90000
   macro avg       0.92      0.92      0.92     90000
weighted avg       0.92      0.92      0.92     90000



In [17]:
import time
start=time.time()
from sklearn.ensemble import AdaBoostClassifier
abc = AdaBoostClassifier()

# Train Adaboost Classifer
model = abc.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Adaboost-ACCURACY => "+str(metrics.accuracy_score(y_test, y_pred)*100)+str(" %"))
end=time.time()
print("time="+str(end-start))


#CLASSIFICATION REPORT
from sklearn.metrics import classification_report,confusion_matrix
#CONFUSION MATRIX
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Adaboost-ACCURACY => 83.08555555555556 %
time=136.58350372314453
[[24277  2815  3039]
 [ 1768 25883  2280]
 [ 2498  2823 24617]]


              precision    recall  f1-score   support

           0       0.85      0.81      0.83     30131
           1       0.82      0.86      0.84     29931
           2       0.82      0.82      0.82     29938

    accuracy                           0.83     90000
   macro avg       0.83      0.83      0.83     90000
weighted avg       0.83      0.83      0.83     90000



In [30]:

#DECISION TREE
print("******************DECISION TREE***********************\n")
import time
Start = time.time ()
from sklearn.tree import DecisionTreeClassifier 
Decision_tree= DecisionTreeClassifier(criterion = 'gini') 
Decision_tree.fit(X_train, y_train)
Y_pred = Decision_tree.predict(X_test) 
print("Predicted Value :")
print(Y_pred)
    
print("\nConfusion Matrix : model evaluation")
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, Y_pred))
    
print("\n Classification report :")
from sklearn.metrics import classification_report
print(classification_report(y_test, Y_pred))
    
print("\nDecision Tree Accuracy : ")
from sklearn import metrics
print((metrics.accuracy_score(y_test, Y_pred))*100)
a2=(metrics.accuracy_score(y_test, Y_pred))*100
end= time.time()
b2=str(round(end-Start,2))
print(b2)

print("\n\n")

******************DECISION TREE***********************

Predicted Value :
[0 1 1 ... 0 0 2]

Confusion Matrix : model evaluation
[[26721  1386  2024]
 [ 1333 26598  2000]
 [ 1954  2153 25831]]

 Classification report :
              precision    recall  f1-score   support

           0       0.89      0.89      0.89     30131
           1       0.88      0.89      0.89     29931
           2       0.87      0.86      0.86     29938

    accuracy                           0.88     90000
   macro avg       0.88      0.88      0.88     90000
weighted avg       0.88      0.88      0.88     90000


Decision Tree Accuracy : 
87.94444444444444
28.42





# COMMERCE DATASET: 2 LAKH

In [31]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import time

#DISPLAY TOP 5 ROWS
data = pd.read_csv("C:\\machine\\commerce-dataset.csv")
data.head(10)

IQ  ACCOUNTANCY  BUSINESS STUDIES  ECONOMICS   ENGLISH  \
0  0.245119    -0.851747          0.588909   1.529945 -1.611591   
1 -1.168922     0.031583          0.432711  -0.268296  0.970550   
2 -0.041283     0.280792         -0.831895   1.397449  0.550499   
3  0.360363    -0.999669          1.142266   0.133847  2.033926   
4 -0.789811    -0.543417          0.328899   0.428675 -0.024837   
5  2.437267     0.417079          0.085780   0.074520  0.277643   
6 -0.832572     1.629317         -0.582750  -1.784577  0.187788   
7 -0.372833     0.555250         -1.355800   0.605305 -1.212884   
8 -1.460641     0.040167         -0.301129   0.366917 -0.690337   
9  0.277782     0.294056          1.349770  -0.332285  0.040868   

   INFORMATION PRACTICES/MATHEMATICS  LEGAL STUDIES  OPENNESS  \
0                           0.788213      -1.552692  1.256968   
1                          -0.459002      -0.653192  0.801030   
2                           0.377007      -0.800994 -0.671609   
3                          -1.289407       0.317987 -1.182210   
4                           0.310884      -0.601240  0.779158   
5                          -1.103500       0.506591  1.018899   
6                          -0.241932       1.597794  1.016708   
7                          -0.664042       0.238459 -0.662637   
8                          -0.403584       2.284197  1.919773   
9                           0.242230      -1.850002 -1.301307   

   CONSCIENTIOUSNESS  EXTRAVERSION  ...  SATISFACTION  SOCIO-ECONOMIC-FACTORS  \
0           1.603721     -0.122566  ...      0.083766               -0.350558   
1           1.101843      0.549276  ...      1.976195               -0.849972   
2          -0.396741     -1.193091  ...      1.049190                0.382831   
3          -0.572107     -0.562029  ...      0.096847                0.518845   
4          -1.230092     -1.713011  ...      0.565525               -0.280653   
5           1.297995     -0.072008  ...      1.720544               -0.679405   
6          -0.079366      0.185673  ...     -1.718099               -1.335331   
7           0.648457      0.850449  ...      1.830901                0.428492   
8          -0.777661     -0.229758  ...      0.398724                1.917156   
9          -3.079846     -0.497228  ...      0.803789               -0.092071   

    M-SCORE  TEAM-WORK  COMPETIVE-EXAM-WINNER  LEADERSHIP-SKILL  \
0 -0.707781  -2.139185               0.109520         -2.028669   
1  0.374115  -0.103719              -0.376152          0.172232   
2 -0.057216   0.954195              -1.387928          0.048100   
3  1.408462  -1.446753               1.118879         -1.834134   
4 -0.856836   1.392418              -2.515866         -0.713385   
5 -0.116577  -1.581613               1.032171         -1.204232   
6 -0.225129   0.756647               1.467213          0.020342   
7 -1.067491  -1.773033              -0.364809          0.971728   
8  0.916942   1.549282              -0.184433          1.237519   
9  0.110709   2.052555               0.871248          0.747563   

   WORK-LIFE-BALANCE  CERTIFICATIONS  SELF-LEARNING-CAPABILITY  CAREER  
0          -0.739035        0.838250                 -1.972468       0  
1          -1.013076        0.877472                 -0.786797       0  
2           0.567865        0.839897                  0.157779       1  
3          -0.943777       -1.053905                  0.970705       0  
4          -1.397114       -0.798758                 -1.590746       1  
5          -1.584098        0.786545                 -0.092714       0  
6           0.417134       -0.061786                 -0.754360       0  
7          -1.676542        2.402972                 -0.944793       0  
8           1.210530       -0.305860                  0.500771       1  
9           1.316871        0.222439                 -0.003946       2  

[10 rows x 23 columns]

In [32]:
X=data.drop(['CAREER'], axis = 1).values
#data.drop(['name'])
from sklearn import preprocessing 
Standardisation = preprocessing.StandardScaler() 
AFTER_SCALE= Standardisation.fit_transform(X) 
X=AFTER_SCALE
print(X)
y = data['CAREER']
print(X.shape)
print(y.shape)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=0)

[[ 0.24568831 -0.84811566  0.59238466 ... -0.74003098  0.84156985
  -1.97034714]
 [-1.17232281  0.03364377  0.43613436 ... -1.01396808  0.88089232
  -0.78525331]
 [-0.04151851  0.28240994 -0.82889404 ...  0.56637192  0.84322125
   0.15886304]
 ...
 [-0.29430557  0.54732491  1.45868918 ... -0.18934601 -0.09286142
  -1.29003794]
 [-0.19140339  0.17657008  1.24056875 ...  0.47350013 -0.43188206
  -1.85895264]
 [-0.35300072  1.51364061  0.28373126 ... -0.75587931  1.64742374
  -1.16689615]]
(200000, 22)
(200000,)


In [33]:
#NAIVE  BAYES
import time
start=time.time()
import sklearn.metrics as metrics
from sklearn.naive_bayes import GaussianNB
naive=GaussianNB()
naive.fit(X_train,y_train)
y_pred = naive.predict(X_test)
print("'NAIVE-BAYES-ACCURACY => "+str(metrics.accuracy_score(y_test, y_pred)*100)+str(" %"))
end=time.time()
print("Time=",end-start)

#CLASSIFICATION REPORT
from sklearn.metrics import classification_report,confusion_matrix
#CONFUSION MATRIX
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))



'NAIVE-BAYES-ACCURACY => 86.3725 %
Time= 0.13268804550170898
[[11226   427  1645]
 [   93 13000   345]
 [ 2320   621 10323]]


              precision    recall  f1-score   support

           0       0.82      0.84      0.83     13298
           1       0.93      0.97      0.95     13438
           2       0.84      0.78      0.81     13264

    accuracy                           0.86     40000
   macro avg       0.86      0.86      0.86     40000
weighted avg       0.86      0.86      0.86     40000



In [34]:
#logistic regression
import time
start=time.time()
from sklearn import linear_model
log=linear_model.LogisticRegression()


log.fit(X_train,y_train)
y_pred=(log.predict(X_test))
print("LOGISTIC-REGRESSION-ACCURACY => "+str(metrics.accuracy_score(y_test, y_pred)*100)+str(" %"))
end=time.time()
print("time=",end-start)
#CLASSIFICATION REPORT
from sklearn.metrics import classification_report,confusion_matrix
#CONFUSION MATRIX
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

LOGISTIC-REGRESSION-ACCURACY => 93.875 %
time= 2.0929994583129883
[[12620   380   298]
 [  141 12770   527]
 [  777   327 12160]]


              precision    recall  f1-score   support

           0       0.93      0.95      0.94     13298
           1       0.95      0.95      0.95     13438
           2       0.94      0.92      0.93     13264

    accuracy                           0.94     40000
   macro avg       0.94      0.94      0.94     40000
weighted avg       0.94      0.94      0.94     40000



In [35]:
#two hidden layers

import time
start=time.time()

from sklearn.neural_network import MLPClassifier
mlp= MLPClassifier(hidden_layer_sizes=(8,8), activation='relu', solver='adam',max_iter=200)
mlp.fit(X_train,y_train)
y_pred=(mlp.predict(X_test))
print("MLP-ACCURACY => "+str(metrics.accuracy_score(y_test, y_pred)*100)+str(" %"))
end=time.time()
print("time="+str(end-start))

#CLASSIFICATION REPORT
from sklearn.metrics import classification_report,confusion_matrix
#CONFUSION MATRIX
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

MLP-ACCURACY => 97.5125 %
time=56.67140483856201
[[13135    80    83]
 [   54 13232   152]
 [  432   194 12638]]


              precision    recall  f1-score   support

           0       0.96      0.99      0.98     13298
           1       0.98      0.98      0.98     13438
           2       0.98      0.95      0.97     13264

    accuracy                           0.98     40000
   macro avg       0.98      0.98      0.98     40000
weighted avg       0.98      0.98      0.98     40000



In [36]:
import time
start=time.time()
from sklearn.ensemble import AdaBoostClassifier
abc = AdaBoostClassifier()

# Train Adaboost Classifer
model = abc.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Adaboost-ACCURACY => "+str(metrics.accuracy_score(y_test, y_pred)*100)+str(" %"))
end=time.time()
print("time="+str(end-start))


#CLASSIFICATION REPORT
from sklearn.metrics import classification_report,confusion_matrix
#CONFUSION MATRIX
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Adaboost-ACCURACY => 90.535 %
time=36.084197998046875
[[11773   320  1205]
 [  595 12477   366]
 [  867   433 11964]]


              precision    recall  f1-score   support

           0       0.89      0.89      0.89     13298
           1       0.94      0.93      0.94     13438
           2       0.88      0.90      0.89     13264

    accuracy                           0.91     40000
   macro avg       0.91      0.91      0.91     40000
weighted avg       0.91      0.91      0.91     40000



In [37]:

#DECISION TREE
print("******************DECISION TREE***********************\n")
import time
Start = time.time ()
from sklearn.tree import DecisionTreeClassifier 
Decision_tree= DecisionTreeClassifier(criterion = 'gini') 
Decision_tree.fit(X_train, y_train)
Y_pred = Decision_tree.predict(X_test) 
print("Predicted Value :")
print(Y_pred)
    
print("\nConfusion Matrix : model evaluation")
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, Y_pred))
    
print("\n Classification report :")
from sklearn.metrics import classification_report
print(classification_report(y_test, Y_pred))
    
print("\nDecision Tree Accuracy : ")
from sklearn import metrics
print((metrics.accuracy_score(y_test, Y_pred))*100)
a2=(metrics.accuracy_score(y_test, Y_pred))*100
end= time.time()
b2=str(round(end-Start,2))
print(b2)

print("\n\n")

******************DECISION TREE***********************

Predicted Value :
[1 0 0 ... 2 1 0]

Confusion Matrix : model evaluation
[[12600   164   534]
 [  156 12968   314]
 [  502   337 12425]]

 Classification report :
              precision    recall  f1-score   support

           0       0.95      0.95      0.95     13298
           1       0.96      0.97      0.96     13438
           2       0.94      0.94      0.94     13264

    accuracy                           0.95     40000
   macro avg       0.95      0.95      0.95     40000
weighted avg       0.95      0.95      0.95     40000


Decision Tree Accuracy : 
94.9825
12.72





# HUMAITIES DATASET - 1.5 LAKH

In [46]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import time

#DISPLAY TOP 5 ROWS
data = pd.read_csv("C:\\machine\\humanities-dataset.csv")
data.head(10)

IQ   HISTORY  ECONOMICS  SOCIOLOGY  GEOGRAPHY  POLITICAL SCIENCE  \
0  1.651165  1.300911  -1.353804  -0.798610   0.329610          -0.261548   
1  0.791091  2.197572   0.245021  -0.802328   0.235874           0.005891   
2  1.377100  1.698003   0.855287   1.521133  -0.384961           0.271486   
3 -1.635528  1.250182  -0.270923   0.094553   0.436016           0.800798   
4 -0.545640  0.361642   0.538216   0.678140  -0.772476          -0.152779   
5 -0.628001 -0.427956   0.220561   1.528417  -1.352700           0.945923   
6 -0.593207  1.973183  -1.045402   0.909100   0.282931          -0.447765   
7  0.211892 -0.200643   0.392068  -0.923973  -0.911943           0.156456   
8  0.087132 -1.758586  -0.437291  -0.937863  -1.048539          -2.785045   
9  0.406793  0.652580   0.829022  -0.292334   1.435747           0.408889   

   LANGUAGE  OPENNESS  CONSCIENTIOUSNESS  EXTRAVERSION  ...  SATISFACTION  \
0 -0.957768 -1.955050           0.513994     -1.158827  ...     -0.811830   
1 -0.310359  0.267041          -0.002142     -1.418743  ...     -0.418400   
2 -0.387395  0.386461          -0.283040      1.512270  ...     -0.247391   
3 -1.752165 -0.899055           1.683146     -1.498247  ...     -0.371508   
4  1.464910 -0.388882          -0.505807     -0.160456  ...      1.142675   
5  1.592168  0.791029          -0.562641     -1.879086  ...     -0.030126   
6  2.042927  0.468185           1.038957      0.103532  ...     -1.367649   
7 -0.526392  1.615690          -0.296108      0.674054  ...      0.560056   
8  1.225086  0.295614          -0.674979     -1.638797  ...     -1.459069   
9  0.551696 -0.367750           0.293027      0.125824  ...      0.561043   

   SOCIO-ECONOMIC-FACTORS   M-SCORE  TEAM-WORK  COMPETIVE-EXAM-WINNER  \
0               -0.157286  0.162584   0.204840              -1.601923   
1               -0.273882 -0.235674  -0.677657              -0.685583   
2               -0.191357  0.147334  -0.457842               0.778543   
3                0.343312 -1.115507  -1.675611               0.212248   
4               -0.453620  0.182175   1.009956               2.127781   
5               -0.443133 -1.010602  -0.683892               0.944334   
6               -0.719364  0.750667  -0.984020               0.706671   
7               -1.708477 -3.576407   0.194535              -2.457085   
8                2.336478 -1.444683   0.178842              -0.596059   
9                1.405128 -0.316851   0.300638              -0.490581   

   LEADERSHIP-SKILL  WORK-LIFE-BALANCE  CERTIFICATIONS  \
0          0.363536          -1.526603       -1.311694   
1          0.825671          -1.495240       -0.453347   
2         -0.829255          -0.222240        0.605101   
3          0.345293           1.509444       -0.838128   
4          0.255813           0.893201       -1.166986   
5          0.517078           1.368210       -0.428064   
6          0.764143          -1.719395       -1.503220   
7         -0.648021          -0.115144       -2.029960   
8         -1.407105           0.277610       -0.818494   
9          0.091890           0.329685        2.219113   

   SELF-LEARNING-CAPABILITY  CAREER  
0                  1.435085       1  
1                  1.257949       1  
2                  1.111774       2  
3                 -0.063052       0  
4                 -1.092004       2  
5                 -1.655066       0  
6                  1.297374       0  
7                 -0.180381       1  
8                 -0.009591       1  
9                 -0.253444       2  

[10 rows x 23 columns]

In [47]:
X=data.drop(['CAREER'], axis = 1).values
#data.drop(['name'])
from sklearn import preprocessing 
Standardisation = preprocessing.StandardScaler() 
AFTER_SCALE= Standardisation.fit_transform(X) 
X=AFTER_SCALE
print(X)
y = data['CAREER']
print(X.shape)
print(y.shape)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=0)

[[ 1.65387287  1.29905166 -1.35037826 ... -1.53645037 -0.59739747
   1.43158727]
 [ 0.79354715  2.19748708  0.24791042 ... -1.505026   -0.07371361
   1.25453011]
 [ 1.37972835  1.69692931  0.85797214 ... -0.22954282  0.57205402
   1.10842098]
 ...
 [ 1.23653922 -1.60844464 -1.50510814 ... -0.68939418  0.00466291
  -1.06779219]
 [ 1.75261127  1.08815958 -0.06227623 ...  0.86284206 -0.17064843
   1.33240845]
 [ 0.08564096 -0.92033662  0.91763489 ...  0.62457878 -0.495897
   0.29817691]]
(150000, 22)
(150000,)


In [48]:
#NAIVE  BAYES
import time
start=time.time()
import sklearn.metrics as metrics
from sklearn.naive_bayes import GaussianNB
naive=GaussianNB()
naive.fit(X_train,y_train)
y_pred = naive.predict(X_test)
print("'NAIVE-BAYES-ACCURACY => "+str(metrics.accuracy_score(y_test, y_pred)*100)+str(" %"))
end=time.time()
print("Time=",end-start)

#CLASSIFICATION REPORT
from sklearn.metrics import classification_report,confusion_matrix
#CONFUSION MATRIX
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))



'NAIVE-BAYES-ACCURACY => 83.90333333333334 %
Time= 0.1116337776184082
[[7993  456 1511]
 [ 495 8114 1380]
 [ 140  847 9064]]


              precision    recall  f1-score   support

           0       0.93      0.80      0.86      9960
           1       0.86      0.81      0.84      9989
           2       0.76      0.90      0.82     10051

    accuracy                           0.84     30000
   macro avg       0.85      0.84      0.84     30000
weighted avg       0.85      0.84      0.84     30000



In [49]:
#logistic regression
import time
start=time.time()
from sklearn import linear_model
log=linear_model.LogisticRegression()


log.fit(X_train,y_train)
y_pred=(log.predict(X_test))
print("LOGISTIC-REGRESSION-ACCURACY => "+str(metrics.accuracy_score(y_test, y_pred)*100)+str(" %"))
end=time.time()
print("time=",end-start)
#CLASSIFICATION REPORT
from sklearn.metrics import classification_report,confusion_matrix
#CONFUSION MATRIX
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

LOGISTIC-REGRESSION-ACCURACY => 83.51666666666667 %
time= 1.1849126815795898
[[8660  396  904]
 [ 562 8091 1336]
 [ 607 1140 8304]]


              precision    recall  f1-score   support

           0       0.88      0.87      0.88      9960
           1       0.84      0.81      0.82      9989
           2       0.79      0.83      0.81     10051

    accuracy                           0.84     30000
   macro avg       0.84      0.84      0.84     30000
weighted avg       0.84      0.84      0.84     30000



In [50]:
#two hidden layers

import time
start=time.time()

from sklearn.neural_network import MLPClassifier
mlp= MLPClassifier(hidden_layer_sizes=(8,8), activation='relu', solver='adam',max_iter=200)
mlp.fit(X_train,y_train)
y_pred=(mlp.predict(X_test))
print("MLP-ACCURACY => "+str(metrics.accuracy_score(y_test, y_pred)*100)+str(" %"))
end=time.time()
print("time="+str(end-start))

#CLASSIFICATION REPORT
from sklearn.metrics import classification_report,confusion_matrix
#CONFUSION MATRIX
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

MLP-ACCURACY => 91.14333333333333 %
time=39.442617654800415
[[8958  224  778]
 [ 190 9315  484]
 [ 364  617 9070]]


              precision    recall  f1-score   support

           0       0.94      0.90      0.92      9960
           1       0.92      0.93      0.92      9989
           2       0.88      0.90      0.89     10051

    accuracy                           0.91     30000
   macro avg       0.91      0.91      0.91     30000
weighted avg       0.91      0.91      0.91     30000



In [51]:
import time
start=time.time()
from sklearn.ensemble import AdaBoostClassifier
abc = AdaBoostClassifier()

# Train Adaboost Classifer
model = abc.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Adaboost-ACCURACY => "+str(metrics.accuracy_score(y_test, y_pred)*100)+str(" %"))
end=time.time()
print("time="+str(end-start))


#CLASSIFICATION REPORT
from sklearn.metrics import classification_report,confusion_matrix
#CONFUSION MATRIX
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Adaboost-ACCURACY => 82.91 %
time=26.657072067260742
[[8771  224  965]
 [ 240 8678 1071]
 [1272 1355 7424]]


              precision    recall  f1-score   support

           0       0.85      0.88      0.87      9960
           1       0.85      0.87      0.86      9989
           2       0.78      0.74      0.76     10051

    accuracy                           0.83     30000
   macro avg       0.83      0.83      0.83     30000
weighted avg       0.83      0.83      0.83     30000



In [52]:

#DECISION TREE
print("******************DECISION TREE***********************\n")
import time
Start = time.time ()
from sklearn.tree import DecisionTreeClassifier 
Decision_tree= DecisionTreeClassifier(criterion = 'gini') 
Decision_tree.fit(X_train, y_train)
Y_pred = Decision_tree.predict(X_test) 
print("Predicted Value :")
print(Y_pred)
    
print("\nConfusion Matrix : model evaluation")
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, Y_pred))
    
print("\n Classification report :")
from sklearn.metrics import classification_report
print(classification_report(y_test, Y_pred))
    
print("\nDecision Tree Accuracy : ")
from sklearn import metrics
print((metrics.accuracy_score(y_test, Y_pred))*100)
a2=(metrics.accuracy_score(y_test, Y_pred))*100
end= time.time()
b2=str(round(end-Start,2))
print(b2)

print("\n\n")

******************DECISION TREE***********************

Predicted Value :
[1 1 1 ... 0 2 1]

Confusion Matrix : model evaluation
[[8739  384  837]
 [ 385 8809  795]
 [ 919  779 8353]]

 Classification report :
              precision    recall  f1-score   support

           0       0.87      0.88      0.87      9960
           1       0.88      0.88      0.88      9989
           2       0.84      0.83      0.83     10051

    accuracy                           0.86     30000
   macro avg       0.86      0.86      0.86     30000
weighted avg       0.86      0.86      0.86     30000


Decision Tree Accuracy : 
86.33666666666666
8.08



